name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
          java-version: '21'
          distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dungeongate-jar
        path: target/dungeongate-1.0.jar
